[package]
name = "libgit2-sys"
version = "0.12.3+1.0.0"
authors = ["Josh Triplett <josh@joshtriplett.org>", "Alex Crichton <alex@alexcrichton.com>"]
links = "git2"
build = "build.rs"
repository = "https://github.com/rust-lang/git2-rs"
license = "MIT/Apache-2.0"
description = "Native bindings to the libgit2 library"
exclude = [
    "libgit2/tests/*",
]
edition = "2018"

[lib]
name = "libgit2_sys"
path = "lib.rs"

[dependencies]
libc = "0.2"
libssh2-sys = { path = "../../ssh2-rs/libssh2-sys", optional = true }
libz-sys = "1.0.22"

[build-dependencies]
pkg-config = "0.3.7"
cc = { version = "1.0.42", features = ['parallel'] }

[target.'cfg(unix)'.dependencies]
openssl-sys = { version = "0.9", optional = true, features = [ "vendored" ] }

[features]
ssh = ["libssh2-sys"]
https = ["openssl-sys"]
ssh_key_from_memory = []
